language: node_js
node_js:
  - 12
cache: npm
os: linux # linux of windows
dist: bionic # bionic for 18.04, focal for 20.04 ,default is xenial 16.04
branches:
  only:
    - master # build master branch only
before_install:
  - export TZ='Asia/Shanghai'
install:
  - npm install
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  cleanup: false
  keep_history: true
  token: $GH_TOKEN
  on:
    branch: master
  local_dir: public
